--region *.lua
--Date
--此文件由[BabeLua]插件自动生成

local mahjongType = {
    [0]   = { folder = "", resource = "mjpai01", audio = "1tiao",     name = "1tiao",     class = 1, },
    [1]   = { folder = "", resource = "mjpai01", audio = "1tiao",     name = "1tiao",     class = 1, },
    [2]   = { folder = "", resource = "mjpai01", audio = "1tiao",     name = "1tiao",     class = 1, },
    [3]   = { folder = "", resource = "mjpai01", audio = "1tiao",     name = "1tiao",     class = 1, },
    [4]   = { folder = "", resource = "mjpai02", audio = "2tiao",     name = "2tiao",     class = 1, },
    [5]   = { folder = "", resource = "mjpai02", audio = "2tiao",     name = "2tiao",     class = 1, },
    [6]   = { folder = "", resource = "mjpai02", audio = "2tiao",     name = "2tiao",     class = 1, },
    [7]   = { folder = "", resource = "mjpai02", audio = "2tiao",     name = "2tiao",     class = 1, },
    [8]   = { folder = "", resource = "mjpai03", audio = "3tiao",     name = "3tiao",     class = 1, },
    [9]   = { folder = "", resource = "mjpai03", audio = "3tiao",     name = "3tiao",     class = 1, },
    [10]  = { folder = "", resource = "mjpai03", audio = "3tiao",     name = "3tiao",     class = 1, },
    [11]  = { folder = "", resource = "mjpai03", audio = "3tiao",     name = "3tiao",     class = 1, },
    [12]  = { folder = "", resource = "mjpai04", audio = "4tiao",     name = "4tiao",     class = 1, },
    [13]  = { folder = "", resource = "mjpai04", audio = "4tiao",     name = "4tiao",     class = 1, },
    [14]  = { folder = "", resource = "mjpai04", audio = "4tiao",     name = "4tiao",     class = 1, },
    [15]  = { folder = "", resource = "mjpai04", audio = "4tiao",     name = "4tiao",     class = 1, },
    [16]  = { folder = "", resource = "mjpai05", audio = "5tiao",     name = "5tiao",     class = 1, },
    [17]  = { folder = "", resource = "mjpai05", audio = "5tiao",     name = "5tiao",     class = 1, },
    [18]  = { folder = "", resource = "mjpai05", audio = "5tiao",     name = "5tiao",     class = 1, },
    [19]  = { folder = "", resource = "mjpai05", audio = "5tiao",     name = "5tiao",     class = 1, },
    [20]  = { folder = "", resource = "mjpai06", audio = "6tiao",     name = "6tiao",     class = 1, },
    [21]  = { folder = "", resource = "mjpai06", audio = "6tiao",     name = "6tiao",     class = 1, },
    [22]  = { folder = "", resource = "mjpai06", audio = "6tiao",     name = "6tiao",     class = 1, },
    [23]  = { folder = "", resource = "mjpai06", audio = "6tiao",     name = "6tiao",     class = 1, },
    [24]  = { folder = "", resource = "mjpai07", audio = "7tiao",     name = "7tiao",     class = 1, },
    [25]  = { folder = "", resource = "mjpai07", audio = "7tiao",     name = "7tiao",     class = 1, },
    [26]  = { folder = "", resource = "mjpai07", audio = "7tiao",     name = "7tiao",     class = 1, },
    [27]  = { folder = "", resource = "mjpai07", audio = "7tiao",     name = "7tiao",     class = 1, },
    [28]  = { folder = "", resource = "mjpai08", audio = "8tiao",     name = "8tiao",     class = 1, },
    [29]  = { folder = "", resource = "mjpai08", audio = "8tiao",     name = "8tiao",     class = 1, },
    [30]  = { folder = "", resource = "mjpai08", audio = "8tiao",     name = "8tiao",     class = 1, },
    [31]  = { folder = "", resource = "mjpai08", audio = "8tiao",     name = "8tiao",     class = 1, },
    [32]  = { folder = "", resource = "mjpai09", audio = "9tiao",     name = "9tiao",     class = 1, },
    [33]  = { folder = "", resource = "mjpai09", audio = "9tiao",     name = "9tiao",     class = 1, },
    [34]  = { folder = "", resource = "mjpai09", audio = "9tiao",     name = "9tiao",     class = 1, },
    [35]  = { folder = "", resource = "mjpai09", audio = "9tiao",     name = "9tiao",     class = 1, },
    [36]  = { folder = "", resource = "mjpai19", audio = "1tong",     name = "1tong",     class = 2, },
    [37]  = { folder = "", resource = "mjpai19", audio = "1tong",     name = "1tong",     class = 2, },
    [38]  = { folder = "", resource = "mjpai19", audio = "1tong",     name = "1tong",     class = 2, },
    [39]  = { folder = "", resource = "mjpai19", audio = "1tong",     name = "1tong",     class = 2, },
    [40]  = { folder = "", resource = "mjpai20", audio = "2tong",     name = "2tong",     class = 2, },
    [41]  = { folder = "", resource = "mjpai20", audio = "2tong",     name = "2tong",     class = 2, },
    [42]  = { folder = "", resource = "mjpai20", audio = "2tong",     name = "2tong",     class = 2, },
    [43]  = { folder = "", resource = "mjpai20", audio = "2tong",     name = "2tong",     class = 2, },
    [44]  = { folder = "", resource = "mjpai21", audio = "3tong",     name = "3tong",     class = 2, },
    [45]  = { folder = "", resource = "mjpai21", audio = "3tong",     name = "3tong",     class = 2, },
    [46]  = { folder = "", resource = "mjpai21", audio = "3tong",     name = "3tong",     class = 2, },
    [47]  = { folder = "", resource = "mjpai21", audio = "3tong",     name = "3tong",     class = 2, },
    [48]  = { folder = "", resource = "mjpai22", audio = "4tong",     name = "4tong",     class = 2, },
    [49]  = { folder = "", resource = "mjpai22", audio = "4tong",     name = "4tong",     class = 2, },
    [50]  = { folder = "", resource = "mjpai22", audio = "4tong",     name = "4tong",     class = 2, },
    [51]  = { folder = "", resource = "mjpai22", audio = "4tong",     name = "4tong",     class = 2, },
    [52]  = { folder = "", resource = "mjpai23", audio = "5tong",     name = "5tong",     class = 2, },
    [53]  = { folder = "", resource = "mjpai23", audio = "5tong",     name = "5tong",     class = 2, },
    [54]  = { folder = "", resource = "mjpai23", audio = "5tong",     name = "5tong",     class = 2, },
    [55]  = { folder = "", resource = "mjpai23", audio = "5tong",     name = "5tong",     class = 2, },
    [56]  = { folder = "", resource = "mjpai24", audio = "6tong",     name = "6tong",     class = 2, },
    [57]  = { folder = "", resource = "mjpai24", audio = "6tong",     name = "6tong",     class = 2, },
    [58]  = { folder = "", resource = "mjpai24", audio = "6tong",     name = "6tong",     class = 2, },
    [59]  = { folder = "", resource = "mjpai24", audio = "6tong",     name = "6tong",     class = 2, },
    [60]  = { folder = "", resource = "mjpai25", audio = "7tong",     name = "7tong",     class = 2, },
    [61]  = { folder = "", resource = "mjpai25", audio = "7tong",     name = "7tong",     class = 2, },
    [62]  = { folder = "", resource = "mjpai25", audio = "7tong",     name = "7tong",     class = 2, },
    [63]  = { folder = "", resource = "mjpai25", audio = "7tong",     name = "7tong",     class = 2, },
    [64]  = { folder = "", resource = "mjpai26", audio = "8tong",     name = "8tong",     class = 2, },
    [65]  = { folder = "", resource = "mjpai26", audio = "8tong",     name = "8tong",     class = 2, },
    [66]  = { folder = "", resource = "mjpai26", audio = "8tong",     name = "8tong",     class = 2, },
    [67]  = { folder = "", resource = "mjpai26", audio = "8tong",     name = "8tong",     class = 2, },
    [68]  = { folder = "", resource = "mjpai27", audio = "9tong",     name = "9tong",     class = 2, },
    [69]  = { folder = "", resource = "mjpai27", audio = "9tong",     name = "9tong",     class = 2, },
    [70]  = { folder = "", resource = "mjpai27", audio = "9tong",     name = "9tong",     class = 2, },
    [71]  = { folder = "", resource = "mjpai27", audio = "9tong",     name = "9tong",     class = 2, },
    [72]  = { folder = "", resource = "mjpai10", audio = "1wan",      name = "1wan",      class = 3, },
    [73]  = { folder = "", resource = "mjpai10", audio = "1wan",      name = "1wan",      class = 3, },
    [74]  = { folder = "", resource = "mjpai10", audio = "1wan",      name = "1wan",      class = 3, },
    [75]  = { folder = "", resource = "mjpai10", audio = "1wan",      name = "1wan",      class = 3, },
    [76]  = { folder = "", resource = "mjpai11", audio = "2wan",      name = "2wan",      class = 3, },
    [77]  = { folder = "", resource = "mjpai11", audio = "2wan",      name = "2wan",      class = 3, },
    [78]  = { folder = "", resource = "mjpai11", audio = "2wan",      name = "2wan",      class = 3, },
    [79]  = { folder = "", resource = "mjpai11", audio = "2wan",      name = "2wan",      class = 3, },
    [80]  = { folder = "", resource = "mjpai12", audio = "3wan",      name = "3wan",      class = 3, },
    [81]  = { folder = "", resource = "mjpai12", audio = "3wan",      name = "3wan",      class = 3, },
    [82]  = { folder = "", resource = "mjpai12", audio = "3wan",      name = "3wan",      class = 3, },
    [83]  = { folder = "", resource = "mjpai12", audio = "3wan",      name = "3wan",      class = 3, },
    [84]  = { folder = "", resource = "mjpai13", audio = "4wan",      name = "4wan",      class = 3, },
    [85]  = { folder = "", resource = "mjpai13", audio = "4wan",      name = "4wan",      class = 3, },
    [86]  = { folder = "", resource = "mjpai13", audio = "4wan",      name = "4wan",      class = 3, },
    [87]  = { folder = "", resource = "mjpai13", audio = "4wan",      name = "4wan",      class = 3, },
    [88]  = { folder = "", resource = "mjpai14", audio = "5wan",      name = "5wan",      class = 3, },
    [89]  = { folder = "", resource = "mjpai14", audio = "5wan",      name = "5wan",      class = 3, },
    [90]  = { folder = "", resource = "mjpai14", audio = "5wan",      name = "5wan",      class = 3, },
    [91]  = { folder = "", resource = "mjpai14", audio = "5wan",      name = "5wan",      class = 3, },
    [92]  = { folder = "", resource = "mjpai15", audio = "6wan",      name = "6wan",      class = 3, },
    [93]  = { folder = "", resource = "mjpai15", audio = "6wan",      name = "6wan",      class = 3, },
    [94]  = { folder = "", resource = "mjpai15", audio = "6wan",      name = "6wan",      class = 3, },
    [95]  = { folder = "", resource = "mjpai15", audio = "6wan",      name = "6wan",      class = 3, },
    [96]  = { folder = "", resource = "mjpai16", audio = "7wan",      name = "7wan",      class = 3, },
    [97]  = { folder = "", resource = "mjpai16", audio = "7wan",      name = "7wan",      class = 3, },
    [98]  = { folder = "", resource = "mjpai16", audio = "7wan",      name = "7wan",      class = 3, },
    [99]  = { folder = "", resource = "mjpai16", audio = "7wan",      name = "7wan",      class = 3, },
    [100] = { folder = "", resource = "mjpai17", audio = "8wan",      name = "8wan",      class = 3, },
    [101] = { folder = "", resource = "mjpai17", audio = "8wan",      name = "8wan",      class = 3, },
    [102] = { folder = "", resource = "mjpai17", audio = "8wan",      name = "8wan",      class = 3, },
    [103] = { folder = "", resource = "mjpai17", audio = "8wan",      name = "8wan",      class = 3, },
    [104] = { folder = "", resource = "mjpai18", audio = "9wan",      name = "9wan",      class = 3, },
    [105] = { folder = "", resource = "mjpai18", audio = "9wan",      name = "9wan",      class = 3, },
    [106] = { folder = "", resource = "mjpai18", audio = "9wan",      name = "9wan",      class = 3, },
    [107] = { folder = "", resource = "mjpai18", audio = "9wan",      name = "9wan",      class = 3, },
    [108] = { folder = "", resource = "mjpai32", audio = "hongzhong", name = "hongzhong", class = 4, },
    [109] = { folder = "", resource = "mjpai32", audio = "hongzhong", name = "hongzhong", class = 4, },
    [110] = { folder = "", resource = "mjpai32", audio = "hongzhong", name = "hongzhong", class = 4, },
    [111] = { folder = "", resource = "mjpai32", audio = "hongzhong", name = "hongzhong", class = 4, },
    [112] = { folder = "", resource = "mjpai33", audio = "fa",        name = "facai",     class = 4, },
    [113] = { folder = "", resource = "mjpai33", audio = "fa",        name = "facai",     class = 4, },
    [114] = { folder = "", resource = "mjpai33", audio = "fa",        name = "facai",     class = 4, },
    [115] = { folder = "", resource = "mjpai33", audio = "fa",        name = "facai",     class = 4, },
    [116] = { folder = "", resource = "mjpai34", audio = "bai",       name = "baiban",    class = 4, },
    [117] = { folder = "", resource = "mjpai34", audio = "bai",       name = "baiban",    class = 4, },
    [118] = { folder = "", resource = "mjpai34", audio = "bai",       name = "baiban",    class = 4, },
    [119] = { folder = "", resource = "mjpai34", audio = "bai",       name = "baiban",    class = 4, },
}

local mahjongClassName = {
    "tiao",
    "tong",
    "wan",
    "other",
}

function getMahjongClassName(mahjongClass)
    return mahjongClassName[mahjongClass]
end

return mahjongType

--endregion
