//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class AndroidHelperWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(AndroidHelper), typeof(System.Object));
		L.RegFunction("ShowErrorMessage", ShowErrorMessage);
		L.RegFunction("LoginWX", LoginWX);
		L.RegFunction("ShareTextWX", ShareTextWX);
		L.RegFunction("ShareUrlWX", ShareUrlWX);
		L.RegFunction("ShareImageWX", ShareImageWX);
		L.RegFunction("ShareTextSG", ShareTextSG);
		L.RegFunction("ShareImageSG", ShareImageSG);
		L.RegFunction("OnLoginWxHandler", OnLoginWxHandler);
		L.RegFunction("New", _CreateAndroidHelper);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("instance", get_instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateAndroidHelper(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				AndroidHelper obj = new AndroidHelper();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: AndroidHelper.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShowErrorMessage(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AndroidHelper obj = (AndroidHelper)ToLua.CheckObject<AndroidHelper>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.ShowErrorMessage(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoginWX(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AndroidHelper obj = (AndroidHelper)ToLua.CheckObject<AndroidHelper>(L, 1);
			System.Action<string> arg0 = (System.Action<string>)ToLua.CheckDelegate<System.Action<string>>(L, 2);
			obj.LoginWX(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShareTextWX(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			AndroidHelper obj = (AndroidHelper)ToLua.CheckObject<AndroidHelper>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
			obj.ShareTextWX(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShareUrlWX(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 5);
			AndroidHelper obj = (AndroidHelper)ToLua.CheckObject<AndroidHelper>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			string arg2 = ToLua.CheckString(L, 4);
			bool arg3 = LuaDLL.luaL_checkboolean(L, 5);
			obj.ShareUrlWX(arg0, arg1, arg2, arg3);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShareImageWX(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			AndroidHelper obj = (AndroidHelper)ToLua.CheckObject<AndroidHelper>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
			obj.ShareImageWX(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShareTextSG(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AndroidHelper obj = (AndroidHelper)ToLua.CheckObject<AndroidHelper>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.ShareTextSG(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShareImageSG(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AndroidHelper obj = (AndroidHelper)ToLua.CheckObject<AndroidHelper>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.ShareImageSG(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnLoginWxHandler(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AndroidHelper obj = (AndroidHelper)ToLua.CheckObject<AndroidHelper>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.OnLoginWxHandler(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, AndroidHelper.instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

