//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class AndroidHelperWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(AndroidHelper), typeof(System.Object));
		L.RegFunction("RegisterLoginWXCallback", RegisterLoginWXCallback);
		L.RegFunction("RegisterInviteSGCallback", RegisterInviteSGCallback);
		L.RegFunction("SetLogined", SetLogined);
		L.RegFunction("ShowErrorMessage", ShowErrorMessage);
		L.RegFunction("LoginWX", LoginWX);
		L.RegFunction("ShareTextWX", ShareTextWX);
		L.RegFunction("ShareUrlWX", ShareUrlWX);
		L.RegFunction("ShareImageWX", ShareImageWX);
		L.RegFunction("ShareTextSG", ShareTextSG);
		L.RegFunction("ShareInvitationSG", ShareInvitationSG);
		L.RegFunction("ShareImageSG", ShareImageSG);
		L.RegFunction("GetParamsSG", GetParamsSG);
		L.RegFunction("OnLoginWxHandler", OnLoginWxHandler);
		L.RegFunction("OnInviteSgHandler", OnInviteSgHandler);
		L.RegFunction("New", _CreateAndroidHelper);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("instance", get_instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateAndroidHelper(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				AndroidHelper obj = new AndroidHelper();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: AndroidHelper.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RegisterLoginWXCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AndroidHelper obj = (AndroidHelper)ToLua.CheckObject<AndroidHelper>(L, 1);
			System.Action<string> arg0 = (System.Action<string>)ToLua.CheckDelegate<System.Action<string>>(L, 2);
			obj.RegisterLoginWXCallback(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RegisterInviteSGCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AndroidHelper obj = (AndroidHelper)ToLua.CheckObject<AndroidHelper>(L, 1);
			System.Action<string> arg0 = (System.Action<string>)ToLua.CheckDelegate<System.Action<string>>(L, 2);
			obj.RegisterInviteSGCallback(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetLogined(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AndroidHelper obj = (AndroidHelper)ToLua.CheckObject<AndroidHelper>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetLogined(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShowErrorMessage(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AndroidHelper obj = (AndroidHelper)ToLua.CheckObject<AndroidHelper>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.ShowErrorMessage(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoginWX(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			AndroidHelper obj = (AndroidHelper)ToLua.CheckObject<AndroidHelper>(L, 1);
			obj.LoginWX();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShareTextWX(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			AndroidHelper obj = (AndroidHelper)ToLua.CheckObject<AndroidHelper>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
			obj.ShareTextWX(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShareUrlWX(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 6);
			AndroidHelper obj = (AndroidHelper)ToLua.CheckObject<AndroidHelper>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			string arg2 = ToLua.CheckString(L, 4);
			UnityEngine.Texture2D arg3 = (UnityEngine.Texture2D)ToLua.CheckObject(L, 5, typeof(UnityEngine.Texture2D));
			bool arg4 = LuaDLL.luaL_checkboolean(L, 6);
			obj.ShareUrlWX(arg0, arg1, arg2, arg3, arg4);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShareImageWX(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			AndroidHelper obj = (AndroidHelper)ToLua.CheckObject<AndroidHelper>(L, 1);
			UnityEngine.Texture2D arg0 = (UnityEngine.Texture2D)ToLua.CheckObject(L, 2, typeof(UnityEngine.Texture2D));
			UnityEngine.Texture2D arg1 = (UnityEngine.Texture2D)ToLua.CheckObject(L, 3, typeof(UnityEngine.Texture2D));
			bool arg2 = LuaDLL.luaL_checkboolean(L, 4);
			obj.ShareImageWX(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShareTextSG(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AndroidHelper obj = (AndroidHelper)ToLua.CheckObject<AndroidHelper>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.ShareTextSG(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShareInvitationSG(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 7);
			AndroidHelper obj = (AndroidHelper)ToLua.CheckObject<AndroidHelper>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			UnityEngine.Texture2D arg2 = (UnityEngine.Texture2D)ToLua.CheckObject(L, 4, typeof(UnityEngine.Texture2D));
			string arg3 = ToLua.CheckString(L, 5);
			string arg4 = ToLua.CheckString(L, 6);
			string arg5 = ToLua.CheckString(L, 7);
			obj.ShareInvitationSG(arg0, arg1, arg2, arg3, arg4, arg5);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShareImageSG(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AndroidHelper obj = (AndroidHelper)ToLua.CheckObject<AndroidHelper>(L, 1);
			UnityEngine.Texture2D arg0 = (UnityEngine.Texture2D)ToLua.CheckObject(L, 2, typeof(UnityEngine.Texture2D));
			obj.ShareImageSG(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetParamsSG(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			AndroidHelper obj = (AndroidHelper)ToLua.CheckObject<AndroidHelper>(L, 1);
			string o = obj.GetParamsSG();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnLoginWxHandler(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AndroidHelper obj = (AndroidHelper)ToLua.CheckObject<AndroidHelper>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.OnLoginWxHandler(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnInviteSgHandler(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AndroidHelper obj = (AndroidHelper)ToLua.CheckObject<AndroidHelper>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.OnInviteSgHandler(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, AndroidHelper.instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

