//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class AnimationEventManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(AnimationEventManager), typeof(System.Object));
		L.RegFunction("RegisterTrigger", RegisterTrigger);
		L.RegFunction("OnTrigger", OnTrigger);
		L.RegFunction("UnregisterTrigger", UnregisterTrigger);
		L.RegFunction("Clear", Clear);
		L.RegFunction("New", _CreateAnimationEventManager);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("instance", get_instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateAnimationEventManager(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				AnimationEventManager obj = new AnimationEventManager();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: AnimationEventManager.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RegisterTrigger(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			AnimationEventManager obj = (AnimationEventManager)ToLua.CheckObject<AnimationEventManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			System.Action arg1 = (System.Action)ToLua.CheckDelegate<System.Action>(L, 3);
			obj.RegisterTrigger(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnTrigger(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AnimationEventManager obj = (AnimationEventManager)ToLua.CheckObject<AnimationEventManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.OnTrigger(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnregisterTrigger(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AnimationEventManager obj = (AnimationEventManager)ToLua.CheckObject<AnimationEventManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.UnregisterTrigger(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Clear(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			AnimationEventManager obj = (AnimationEventManager)ToLua.CheckObject<AnimationEventManager>(L, 1);
			obj.Clear();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, AnimationEventManager.instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

