//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class CSVWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(CSV), typeof(System.Object));
		L.RegFunction("Query", Query);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("instance", get_instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Query(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			CSV obj = (CSV)ToLua.CheckObject<CSV>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string o = obj.Query(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, CSV.instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

