//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class HashWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("Hash");
		L.RegFunction("GetHash", GetHash);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetHash(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			string o = Hash.GetHash(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

