//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaPanel_WidgetTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(LuaPanel.WidgetType));
		L.RegVar("GameObject", get_GameObject, null);
		L.RegVar("Panel", get_Panel, null);
		L.RegVar("Text", get_Text, null);
		L.RegVar("Sprite", get_Sprite, null);
		L.RegVar("Image", get_Image, null);
		L.RegVar("Button", get_Button, null);
		L.RegVar("Toggle", get_Toggle, null);
		L.RegVar("Slider", get_Slider, null);
		L.RegVar("Input", get_Input, null);
		L.RegVar("ScrollView", get_ScrollView, null);
		L.RegVar("ScrollRect", get_ScrollRect, null);
		L.RegVar("PageView", get_PageView, null);
		L.RegVar("Animation", get_Animation, null);
		L.RegVar("HorizontalLayout", get_HorizontalLayout, null);
		L.RegVar("VerticalLayout", get_VerticalLayout, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<LuaPanel.WidgetType>.Check = CheckType;
		StackTraits<LuaPanel.WidgetType>.Push = Push;
	}

	static void Push(IntPtr L, LuaPanel.WidgetType arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(LuaPanel.WidgetType), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GameObject(IntPtr L)
	{
		ToLua.Push(L, LuaPanel.WidgetType.GameObject);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Panel(IntPtr L)
	{
		ToLua.Push(L, LuaPanel.WidgetType.Panel);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Text(IntPtr L)
	{
		ToLua.Push(L, LuaPanel.WidgetType.Text);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Sprite(IntPtr L)
	{
		ToLua.Push(L, LuaPanel.WidgetType.Sprite);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Image(IntPtr L)
	{
		ToLua.Push(L, LuaPanel.WidgetType.Image);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Button(IntPtr L)
	{
		ToLua.Push(L, LuaPanel.WidgetType.Button);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Toggle(IntPtr L)
	{
		ToLua.Push(L, LuaPanel.WidgetType.Toggle);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Slider(IntPtr L)
	{
		ToLua.Push(L, LuaPanel.WidgetType.Slider);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Input(IntPtr L)
	{
		ToLua.Push(L, LuaPanel.WidgetType.Input);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ScrollView(IntPtr L)
	{
		ToLua.Push(L, LuaPanel.WidgetType.ScrollView);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ScrollRect(IntPtr L)
	{
		ToLua.Push(L, LuaPanel.WidgetType.ScrollRect);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PageView(IntPtr L)
	{
		ToLua.Push(L, LuaPanel.WidgetType.PageView);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Animation(IntPtr L)
	{
		ToLua.Push(L, LuaPanel.WidgetType.Animation);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_HorizontalLayout(IntPtr L)
	{
		ToLua.Push(L, LuaPanel.WidgetType.HorizontalLayout);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_VerticalLayout(IntPtr L)
	{
		ToLua.Push(L, LuaPanel.WidgetType.VerticalLayout);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		LuaPanel.WidgetType o = (LuaPanel.WidgetType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

