//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class WechatHelperWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(WechatHelper), typeof(System.Object));
		L.RegFunction("Login", Login);
		L.RegFunction("ShareText", ShareText);
		L.RegFunction("ShareUrl", ShareUrl);
		L.RegFunction("ShareImage", ShareImage);
		L.RegFunction("OnLoginHandler", OnLoginHandler);
		L.RegFunction("New", _CreateWechatHelper);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("instance", get_instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateWechatHelper(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				WechatHelper obj = new WechatHelper();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: WechatHelper.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Login(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			WechatHelper obj = (WechatHelper)ToLua.CheckObject<WechatHelper>(L, 1);
			System.Action<string> arg0 = (System.Action<string>)ToLua.CheckDelegate<System.Action<string>>(L, 2);
			obj.Login(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShareText(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			WechatHelper obj = (WechatHelper)ToLua.CheckObject<WechatHelper>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
			obj.ShareText(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShareUrl(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 5);
			WechatHelper obj = (WechatHelper)ToLua.CheckObject<WechatHelper>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			string arg2 = ToLua.CheckString(L, 4);
			bool arg3 = LuaDLL.luaL_checkboolean(L, 5);
			obj.ShareUrl(arg0, arg1, arg2, arg3);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShareImage(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			WechatHelper obj = (WechatHelper)ToLua.CheckObject<WechatHelper>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
			obj.ShareImage(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnLoginHandler(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			WechatHelper obj = (WechatHelper)ToLua.CheckObject<WechatHelper>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.OnLoginHandler(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, WechatHelper.instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

